<?php
/**
 * Default page layout
 */
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title><?php echo $this->title ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="language" content="en" />
		<link rel="stylesheet" type="text/css" href="/static/css/styles.css" />
		<script type="text/javascript" src="/static/js/library.js"></script>
	</head>
	<body>
		<div class="content">
			<header><?php echo $this->title ?></header>
			<?php echo $this->content; ?>
		</div>
	</body>
</html>